package com.tradex.api.enums;

public enum AdminAction {
    LOCK,
    UNLOCK,
    ENABLE,
    DISABLE,
    FORCE_EMAIL_VERIFY,
    PASSWORD_RESET_EMAIL_SENT,
    POINTS_ADJUSTMENT,
    WALLET_ADJUSTMENT,
    CREATE_EMPLOYEE,
    UPDATE_EMPLOYEE_PERMISSIONS,
    DISABLE_EMPLOYEE,
    POINTS_CONVERSION,
    APPROVE_DEPOSIT,
    REJECT_DEPOSIT,
    APPROVE_WITHDRAWAL,
    REJECT_WITHDRAWAL
}
